pipeline {
    agent any
    environment {
        DOCKER_HUB_CREDENTIALS = credentials('docker_hub_creds')
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build and Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker_hub_creds') {
                        def customImage = docker.build("pritish2023/devlab:${env.BUILD_NUMBER}")
                        customImage.push()
                    }
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                sh 'cd terraform/Modules/EC2-Instance && terraform init'
                sh 'cd terraform/Modules/EC2-Instance && terraform apply -auto-approve'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f Kubernetes/kubernetes-deployment.yaml'
            }
        }
    }
}
